### PR TITLE
Ability to turn on minting for owner only (not public mint)

### PR DESCRIPTION
**Pull request by tannerhallman**
I had a use case that I needed the ability to turn on minting, but only want the owner of the collection to be able to mint. This is because we have a controlled collection that I don't want to be publically purchasable (yet). I went ahead and coded that functionality into the SC & the CLI as commands.

I'll attach a PR so you can check it out. I am not in love with my naming convention...

### CODE REVIEW

**Comment by tannerhallman** [comment]
Maybe this would have been better named as "Private Minting"

**Comment by tannerhallman** [comment]
Here's a tx of me turning owner-only mode on
https://devnet-explorer.elrond.com/transactions/842af0bf1c5e57c6bc63ebe671270d4d13332e13088bec1310b9c159bd2ce759

Here's a mint tx that was rejected when owner-only mode was on.
https://devnet-explorer.elrond.com/transactions/dfc44c23d85666bcae0ca4c6d26ac0db6428bdc635811873c6b611c8f4d4a6ec

Here's a tx of me turning it OFF
https://devnet-explorer.elrond.com/transactions/4a11f787df41e1d0318557445e001165fe94550f69008990885b4c462d4ea60f

And here's a tx of me minting with another wallet successfully when it was turned back off
https://devnet-explorer.elrond.com/transactions/0a857c1152d6de264d0c3634dd5679e615bf11f6350809ba5a850015d4c35b0c

**Comment by butavpaul** [comment]
Why not using giveaway fn?
You can use it even if the SC is paused and you can make a giveaway to your address, if I'm not wrong.

**Comment by juliancwirko** [comment]
Hey, thanks for the contribution. I also think that the giveaway does precisely that. But I will review the changes as soon as I fix the Smart Contract.

With a giveaway, you as an owner can send randomly selected tokens to any address you like. You can also send it to your address. I want to keep as few endpoints as possible because it is hard to keep them in order and sync with the CLI tool. And there will probably be some more of them anyway.

**Comment by tannerhallman** [comment]
Thanks for the feedback. For this particular implementation, what I wanted is the ability to actually BLOCK anyone from minting that isn't the owner. This simply creates a mintable collection (but only from the owner's wallet).

If you can use the giveaway endpoint when minting is paused, then I suppose that would accomplish the same thing.

**Comment by tannerhallman** [comment]
After reviewing the code, it does appear that you would be able to use the `giveaway` function, even when while minting is paused. Unless that changes in the future, this PR functionality seems like it overlaps with that state.

No problem. We can close it for now? I also created a PR for the CLI implementing this that can also be closed.

**Pull request closed without merging**
